const seedData = {
  mice: [
    {
      identifier: 3,
      earPunch: "N",
      strain: "C57BL/6N",
      sex: "M",
      dateOfBirth: "01/01/24",
      genotype: "POMC-Cre",
      fatherId: 1,
      motherId: 2,
      cageID: 0,
    },
    {
      identifier: 4,
      earPunch: "R",
      strain: "C57BL/6N",
      sex: "M",
      dateOfBirth: "01/01/24",
      genotype: "POMC-Cre",
      fatherId: 1,
      motherId: 2,
      cageID: 0,
    },
    {
      identifier: 5,
      earPunch: "L",
      strain: "C57BL/6N",
      sex: "M",
      dateOfBirth: "01/01/24",
      genotype: "POMC-Cre",
      fatherId: 1,
      motherId: 2,
      cageID: 0,
    },
    {
      identifier: 6,
      earPunch: "RL",
      strain: "C57BL/6N",
      sex: "M",
      dateOfBirth: "01/01/24",
      genotype: "POMC-Cre",
      fatherId: 1,
      motherId: 2,
      cageID: 0,
    },
    {
      identifier: 7,
      earPunch: "RR",
      strain: "C57BL/6N",
      sex: "M",
      dateOfBirth: "01/01/24",
      genotype: "POMC-Cre",
      fatherId: 1,
      motherId: 2,
      cageID: 0,
    },
    {
      identifier: 8,
      earPunch: "N",
      strain: "C57BL/6N",
      sex: "F",
      dateOfBirth: "01/01/24",
      genotype: "POMC-Cre",
      fatherId: 10,
      motherId: 20,
      cageID: 1,
    },
    {
      identifier: 9,
      earPunch: "R",
      strain: "C57BL/6N",
      sex: "F",
      dateOfBirth: "01/01/24",
      genotype: "POMC-Cre",
      fatherId: 10,
      motherId: 20,
      cageID: 1,
    },
    {
      identifier: 11,
      earPunch: "L",
      strain: "C57BL/6N",
      sex: "F",
      dateOfBirth: "01/01/24",
      genotype: "POMC-Cre",
      fatherId: 10,
      motherId: 20,
      cageID: 1,
    },
    {
      identifier: 12,
      earPunch: "RL",
      strain: "C57BL/6N",
      sex: "F",
      dateOfBirth: "01/01/24",
      genotype: "POMC-Cre",
      fatherId: 10,
      motherId: 20,
      cageID: 1,
    },
    {
      identifier: 13,
      earPunch: "RR",
      strain: "C57BL/6N",
      sex: "F",
      dateOfBirth: "01/01/24",
      genotype: "POMC-Cre",
      fatherId: 10,
      motherId: 20,
      cageID: 1,
    },
    {
      identifier: 14,
      earPunch: "N",
      strain: "C57BL/6N",
      sex: "F",
      dateOfBirth: "01/01/24",
      genotype: "POMC-Cre",
      fatherId: 10,
      motherId: 20,
      cageID: 2,
    },
    {
      identifier: 15,
      earPunch: "R",
      strain: "C57BL/6N",
      sex: "F",
      dateOfBirth: "01/01/24",
      genotype: "POMC-Cre",
      fatherId: 10,
      motherId: 20,
      cageID: 2,
    },
    {
      identifier: 16,
      earPunch: "N",
      strain: "C57BL/6N",
      sex: "M",
      dateOfBirth: "01/01/24",
      genotype: "wild-type",
      fatherId: 10,
      motherId: 20,
      cageID: 2,
    },
    {
      identifier: 17,
      earPunch: "N",
      strain: "C57BL/6N",
      sex: "F",
      dateOfBirth: "01/01/24",
      genotype: "wild-type",
      fatherId: 40,
      motherId: 50,
      cageID: 3,
    },
    {
      identifier: 18,
      earPunch: "R",
      strain: "C57BL/6N",
      sex: "F",
      dateOfBirth: "01/01/24",
      genotype: "wild-type",
      fatherId: 40,
      motherId: 50,
      cageID: 3,
    },
    {
      identifier: 19,
      earPunch: "N",
      strain: "C57BL/6N",
      sex: "M",
      dateOfBirth: "01/01/24",
      genotype: "wild-type",
      fatherId: 40,
      motherId: 50,
      cageID: 3,
    },
  ],

  cages: [
    {
      name: "Stock POMC-Cre males",
      location: "SPF Room 1",
      rack: "Rack 1",
      type: "Stock",
      diet: "Normal diet",
      enrichment: "Normal",
    },
    {
      name: "Stock POMC-Cre females",
      location: "SPF Room 1",
      rack: "Rack 2",
      type: "Stock",
      diet: "Normal diet",
      enrichment: "Normal",
    },
    {
      name: "Breeding POMC-Cre",
      location: "SPF Room 2",
      rack: "Rack 1",
      type: "Breeding",
      diet: "Normal diet",
      enrichment: "Normal",
    },
    {
      name: "Breeding wild-type",
      location: "SPF Room 2",
      rack: "Rack 2",
      type: "Breeding",
      diet: "Normal diet",
      enrichment: "Normal",
    },
  ],
};

module.exports = seedData;
